-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 01:42:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lab1` ;

-- -----------------------------------------------------
-- Table `lab1`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreDepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamento_UNIQUE` (`nombreDepartamento` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `area` FLOAT NOT NULL,
  `presupuesto` INT NOT NULL,
  `gobernador` INT NOT NULL,
  `departamento` INT NOT NULL,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `ubicacionMunicipio_idx` (`departamento` ASC) VISIBLE,
  UNIQUE INDEX `departamento_UNIQUE` (`departamento` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `quienGobierna`
    FOREIGN KEY (`gobernador`)
    REFERENCES `lab1`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ubicacionMunicipio`
    FOREIGN KEY (`departamento`)
    REFERENCES `lab1`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'nn',
  `apellido` VARCHAR(45) NOT NULL DEFAULT 'nn',
  `sexo` INT(2) NOT NULL DEFAULT 0,
  `edad` INT NOT NULL DEFAULT 0,
  `telefono` BIGINT(10) UNSIGNED ZEROFILL NOT NULL DEFAULT '0000000000',
  `vivienda` INT NULL,
  `responsable` INT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `viviendaHabitada_idx` (`vivienda` ASC) VISIBLE,
  INDEX `responsable_idx` (`responsable` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `viviendaHabitada`
    FOREIGN KEY (`vivienda`)
    REFERENCES `lab1`.`vivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `responsable`
    FOREIGN KEY (`responsable`)
    REFERENCES `lab1`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`persona_has_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`persona_has_vivienda` (
  `persona_id` INT NOT NULL,
  `vivienda_id` INT NOT NULL,
  PRIMARY KEY (`persona_id`, `vivienda_id`),
  INDEX `fk_persona_has_vivienda_vivienda1_idx` (`vivienda_id` ASC) VISIBLE,
  INDEX `fk_persona_has_vivienda_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_persona_has_vivienda_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `lab1`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_vivienda_vivienda1`
    FOREIGN KEY (`vivienda_id`)
    REFERENCES `lab1`.`vivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`vivienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `niveles` INT NOT NULL DEFAULT '1',
  `municipio` INT NOT NULL,
  `dueño` INT NOT NULL,
  UNIQUE INDEX `direccion_UNIQUE` (`direccion` ASC) VISIBLE,
  INDEX `ubicadaen_idx` (`municipio` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ubicadaen`
    FOREIGN KEY (`municipio`)
    REFERENCES `lab1`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Agregar primer registro
-- -----------------------------------------------------
INSERT INTO `lab1`.`persona` (id) 
	VALUES ('0');
INSERT INTO `lab1`.`departamento` (`nombreDepartamento`) 
	VALUES ('NN');
INSERT INTO `lab1`.`municipio` (`nombre`, `area`, `presupuesto`, `gobernador`, `departamento`) 
	VALUES ("NN", 0, 0, 0, 0);
INSERT INTO `lab1`.`vivienda` (`direccion`, `capacidad`, `niveles`, `municipio`, `dueño`) 
	VALUES ("NN",1,1,0,0);
INSERT INTO `lab1`.`persona_has_vivienda` (`persona_id`,`vivienda_id`) 
	VALUES (0,0);
UPDATE `lab1`.`persona`
SET `vivienda` = 0, `responsable` = 0 WHERE `id` = 0;

ALTER TABLE `lab1`.`persona` 
DROP FOREIGN KEY `responsable`,
DROP FOREIGN KEY `viviendaHabitada`;
ALTER TABLE `lab1`.`persona` 
CHANGE COLUMN `vivienda` `vivienda` INT NOT NULL ,
CHANGE COLUMN `responsable` `responsable` INT NOT NULL ;
ALTER TABLE `lab1`.`persona` 
ADD CONSTRAINT `responsable`
  FOREIGN KEY (`responsable`)
  REFERENCES `lab1`.`persona` (`id`),
ADD CONSTRAINT `viviendaHabitada`
  FOREIGN KEY (`vivienda`)
  REFERENCES `lab1`.`vivienda` (`id`);